@baseUrl = https://localhost:5001/api
@id = 1

### Get all contacts
GET {{baseUrl}}/contacts

### Get single contact
GET {{baseUrl}}/contacts/{{id}}

### Get single contact (no cache)
GET {{baseUrl}}/contacts/{{id}}
Cache-Control: max-age=0, no-cache

### Create single contact
POST {{baseUrl}}/contacts
Content-Type: application/json

{
    "firstName": "Alice",
    "lastName": "Smith",
    "email": "asmith@unknown.com"
}

### Delete single contact
DELETE {{baseUrl}}/contacts/{{id}}

### Get images (exception)
GET {{baseUrl}}/images
